version: "3"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "4306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
